### ISSUE TITLE
Add opencv to earthscope_insar environment

### ISSUE THREAD

**Issue by bryanvriel** [ASFOpenSARlab/opensarlab-envs#34]
In order to run demos that use both `autoRIFT` and `ISCE`, the `opencv` package needs to be installed. However, `opencv` is missing from the `earthscope_insar_env.yml` file. I tested out adding `opencv` to the dependencies in that yaml file, and everything built and runs successfully. Would it be possible to officially include `opencv` to the list of dependencies?

**Comment by emlundell** [comment]
I added the `opencv` conda package to the yaml. 

https://github.com/ASFOpenSARlab/opensarlab-envs/pull/35
